Algoritmo "areadotriangulo"
// Disciplina   : [Lógica de Programação Com Visualg]
// Professor   : Jailson Costa Dos Santos
// Descrição   : O programa vai solicitar a base, altura e area,
// Autor(a)    : Victor Mariano
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis
   base: real
   altura: real
   area: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva (" Digite a base do triangulo")
   Leia (base)
   Escreva(" Digite a altura do triangulo")
   Leia (altura)
   area <- (base * altura)/2
    Escreva("A area do triangulo é: ", area)
Fimalgoritmo