Algoritmo "ComprimentodaCircunferencia"
// Disciplina  : Lógica de Programação com Visualg
// Professor   : Jailson costa dos santos
// Descrição   : Calcula o comprimento da circunferência
// Autor(a)    : Victor mariano fidelis silva
// Data atual  : 27/03/2026

Var
raio: real
comprimento: real

Inicio
escreva("Digite o raio: ")
leia(raio)

comprimento <- 2 * 3.14 * raio

escreva("O valor do comprimento da circunferência é: ", comprimento)

Fimalgoritmo