Algoritmo "ÁreadoTrapézio"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson costa dos santos
// Descrição   : Solicita a Área do Losango
// Autor(a)    : Victor mariano fidelis silva
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis
basemaior : real
basemenor:real
altura:real
area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite Área do Trapézio maior : ")
leia(basemaior)
escreva("Digite Área do Trapézio menor : ")
leia(basemenor)
escreva("Digite a altura: ")
leia(altura)
area<-(basemaior+basemenor)*altura /2
escreva("O valor da área do Trapézio calculado é : ", area)

Fimalgoritmo