Algoritmo "ÁreadoLosango"
// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson costa dos santos
// Descrição   : Solicita a Área do Losango
// Autor(a)    : Victor mariano fidelis silva
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis
Diagonalmaior: real
diagonalmenor:real
areadoLosango:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite a Diagonal maior : ")
leia(Diagonalmaior)
escreva("Digite a diagonal menor : ")
leia(diagonalmenor)
areadoLosango <-(Diagonalmaior*diagonalmenor)/2
escreva("O valor da área do Losango calculado é : ", areadoLosango)

Fimalgoritmo